In [6]:
# Step 1: Import Necessary Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

# Step 2: Load the Iris Dataset
iris = load_iris()

# Features (X) and target (y)
X = iris.data  # Sepal length, Sepal width, Petal length, Petal width
y = iris.target  # Species

# Convert the dataset to a DataFrame for easier manipulation
df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = iris.target_names[y]

# Step 3: Data Preprocessing
# Standardizing the features (Scaling)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Step 5: Model Selection (Random Forest Classifier)
model = RandomForestClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Step 6: Model Evaluation
y_pred = model.predict(X_test)

# Accuracy Score
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

# Classification Report (Precision, Recall, F1-score)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Step 7: Save the Trained Model
joblib.dump(model, 'iris_rf_model.pkl')
print("Model saved as iris_rf_model.pkl")

# Step 8: Make Predictions
# Example: Predict the species of a new sample (you can modify this to any sample of your choice)
# Sample features: Sepal length, Sepal width, Petal length, Petal width
new_sample = np.array([[5.1, 3.5, 1.4, 0.2]])  # Example: Setosa

# Scale the features (using the same scaler as in training)
new_sample_scaled = scaler.transform(new_sample)

# Predict the species
prediction = loaded_model.predict(new_sample_scaled)

# Output the predicted species
print(f"Predicted species: {iris.target_names[prediction][0]}")


Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Model saved as iris_rf_model.pkl
Predicted species: setosa
